In [1]:
import tensorflow as tf

C:\Users\ya391860\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a=tf.constant('abs')
b=tf.constant('ab')

In [3]:
a+b

<tf.Tensor 'add:0' shape=() dtype=string>

In [4]:
with tf.Session() as s:
    x=s.run(a+b)

In [5]:
x

b'absab'

In [20]:
a=tf.eye(10)
b=tf.zeros((1,5))
c=tf.random_normal((2,5))
d=tf.random_uniform((1,5),minval=0,maxval=10)
ops=[a,b,c,d]
with tf.Session() as s:
    for i in ops:
        print(i.eval())
        print(i)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Tensor("eye_9/MatrixDiag:0", shape=(10, 10), dtype=float32)
[[0. 0. 0. 0. 0.]]
Tensor("zeros_1:0", shape=(1, 5), dtype=float32)
[[-1.7447265   0.6230028  -0.16919826  1.9575235   0.60782874]
 [ 0.3921015   0.07374711  0.6109466   0.30787674  1.3126228 ]]
Tensor("random_normal_1:0", shape=(2, 5), dtype=float32)
[[2.666632 6.568396 9.084463 8.970666 3.46223 ]]
Tensor("random_uniform_1:0", shape=(1, 5), dtype=float32)


In [21]:
a=tf.constant([[1,2],[3,4]])

In [28]:
a.eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [31]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [30]:
a.value_index

0

In [34]:
a.set_shape((2,2))

In [35]:
a.op

<tf.Operation 'Const_2' type=Const>

In [36]:
b=tf.constant([[2],[10]])

In [39]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [41]:
c=tf.matmul(a,b)

In [42]:
with tf.Session() as s:
    print(s.run(c))

[[22]
 [46]]


## TF Graphs

In [43]:
n1=tf.constant(2)
n2=tf.constant(3)
n3=n1+n2

In [44]:
n3.graph

In [46]:
# TF has a default graph
g1=tf.get_default_graph()

In [47]:
g=tf.Graph()

In [48]:
# sets the graph g as default
with g.as_default():
    print(tf.get_default_graph()==g)

True


In [49]:
print(tf.get_default_graph()==g)

False


In [50]:
g1

## TF Variables

In [51]:
b=tf.random_uniform((4,4),minval=0,maxval=10)
v=tf.Variable(initial_value=b)

In [52]:
s=tf.InteractiveSession()

In [53]:
s.run(v)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}} = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable)]]

In [54]:
init = tf.global_variables_initializer()

In [55]:
s.run(init)

In [56]:
s.run(v)

array([[3.3670545 , 2.0436406 , 3.9595103 , 2.3999274 ],
       [2.5524259 , 0.80911994, 0.2948737 , 0.10421515],
       [8.279554  , 3.3213174 , 8.471334  , 4.3872952 ],
       [9.669379  , 0.71235776, 7.2479057 , 0.42675376]], dtype=float32)

In [57]:
ph=tf.placeholder(tf.float32)

In [58]:
ph

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [62]:
s.run(ph,feed_dict={ph:[[1,2]]})

array([[1., 2.]], dtype=float32)

In [64]:
s.close()