In [1]:
import numpy as np
N=100
D=2
X=np.random.randn(N,D)
X[:50,:]=X[:50,:]-2*np.ones(D)
X[50:,:]=X[50:,:]+2*np.ones(D)
Xb=np.concatenate((np.array([np.ones(N)]).T,X),axis=1)
y=np.array([0]*50+[1]*50)
def sigmoid(z):
    return (1/(1+np.exp(-z)))
def cross_entropy(y,y_pred):
    E=0
    for i in range(len(y)):
        if y[i]==1:
            E-=np.log(y_pred[i])
        else:
            E-=np.log(1-y_pred[i])
    return E
w=np.random.randn(D+1)
lr=0.001
cost=[]
for i in range(10000):
    w=w-lr*(np.dot(Xb.T,(sigmoid(Xb.dot(w))-y)))
    y_pred=sigmoid(Xb.dot(w))
    if cross_entropy(y,y_pred)<=0.6:
        break
    cost.append(cross_entropy(y,y_pred))



In [2]:
len(cost)

1779

In [6]:
Xb.shape

(100, 3)

In [8]:
Xb

array([[ 1.        , -1.57436713, -0.95007891],
       [ 1.        , -2.11358236, -3.70049219],
       [ 1.        , -0.15238475, -1.63365749],
       [ 1.        , -0.74926383, -2.35491509],
       [ 1.        , -3.58275502, -3.15561958],
       [ 1.        , -2.49545061, -2.2549482 ],
       [ 1.        , -1.41404355, -0.53569934],
       [ 1.        , -4.25749353, -1.16012071],
       [ 1.        , -0.88205554, -3.73997219],
       [ 1.        , -0.7838374 , -1.99670183],
       [ 1.        , -3.94942505, -2.63978215],
       [ 1.        , -2.49682884, -2.63128045],
       [ 1.        , -2.38692199, -3.6810708 ],
       [ 1.        , -2.73215115, -3.01651163],
       [ 1.        , -1.30017451, -2.0479175 ],
       [ 1.        , -2.895089  , -0.62190233],
       [ 1.        , -1.66169278, -1.99428387],
       [ 1.        , -2.36285473, -1.6276386 ],
       [ 1.        , -2.15859238, -1.64152173],
       [ 1.        , -3.85723513, -1.9007201 ],
       [ 1.        , -1.30559327, -4.007

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
sigmoid(Xb.dot(w)).shape

(100,)

In [14]:
y-np.round(y_pred)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])